services:
  - type: web
    name: pm-agent-backend
    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn -k uvicorn.workers.UvicornWorker main:app

    envVars:
      - key: GEMINI_API_KEY
        sync: false